import jsPDF from 'jspdf';
import { siteConfig } from './config';

function localId(){return `NV-${Date.now().toString(36).toUpperCase()}-${Math.random().toString(36).slice(2,7).toUpperCase()}`}

export async function generateNexVibePdf(opts:{title:string;type:string;summary:string;findings:string[];actions:string[];maskedEmail?:string}){
  const doc=new jsPDF({unit:'mm',format:'a4'});
  const id=localId(); const generated=new Date().toLocaleString();
  try{
    const response=await fetch(siteConfig.logo); const blob=await response.blob();
    const data=await new Promise<string>((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(String(r.result));r.onerror=reject;r.readAsDataURL(blob)});
    doc.addImage(data,'PNG',15,10,24,24);
  }catch{}
  const watermark=()=>{doc.saveGraphicsState();doc.setTextColor(225,225,235);doc.setFontSize(42);doc.text('NEXVIBE',105,155,{angle:35,align:'center'});doc.restoreGraphicsState()}
  watermark();
  doc.setTextColor(16,25,45);doc.setFontSize(18);doc.text(opts.title,46,20);
  doc.setFontSize(10);doc.setTextColor(80,90,110);doc.text(`${opts.type} • ${id}`,46,27);doc.text(`Generated: ${generated}`,46,32);
  let y=44;
  if(opts.maskedEmail){doc.setFontSize(10);doc.text(`Masked email: ${opts.maskedEmail}`,15,y);y+=7}
  const section=(title:string, lines:string[])=>{
    if(y>260){doc.addPage();watermark();y=20}
    doc.setFontSize(13);doc.setTextColor(20,30,50);doc.text(title,15,y);y+=7;
    doc.setFontSize(10);doc.setTextColor(65,75,95);
    for(const line of lines){const wrapped=doc.splitTextToSize(line,175);doc.text(wrapped,15,y);y+=wrapped.length*5+2;if(y>275){doc.addPage();watermark();y=20}}
    y+=4;
  };
  section('Summary',[opts.summary]);
  section('Findings',opts.findings.length?opts.findings:['No findings recorded.']);
  section('Recommended actions',opts.actions);
  section('7-day checklist',['Change weak or reused credentials.','Enable multi-factor authentication where available.','Review account recovery options and active sessions.','Update devices and applications.']);
  section('Limitations',['This report is based only on observable checks and user-confirmed information. It does not guarantee safety, identity, ownership or absence of compromise.']);
  section('Privacy & responsible use',['Generated locally where possible. NexVibe does not intentionally upload personal report data by default. Use security and OSINT tools only for lawful purposes and on systems or data you own or are authorised to investigate.']);
  const pages=doc.getNumberOfPages(); for(let p=1;p<=pages;p++){doc.setPage(p);doc.setFontSize(8);doc.setTextColor(110,120,140);doc.text('Generated by NexVibe Cyber & Digital Hub',105,291,{align:'center'});}
  doc.save(`${id}-${opts.type.toLowerCase().replace(/\s+/g,'-')}.pdf`);
  return id;
}
