import { useEffect, useMemo, useState } from 'react';
import { CheckCircle2, Clock3, Download, FilePlus2, Image, LogOut, Newspaper, RefreshCw, Save, Settings, Trash2, Upload, Wrench, X } from 'lucide-react';
import { useNavigate } from 'react-router-dom';
import { PageHero } from '../components/Common';
import { manualPosts, toolDirectory } from '../data/manual';
import { useLiveNews } from '../lib/live';
import { featureFlags, siteConfig } from '../lib/config';
import type { AdminPost, NewsItem } from '../types';
import { getLocalAdminPosts, saveLocalAdminPosts } from '../lib/localPosts';
import { deleteSupabasePost, fetchSupabaseAdminPosts, upsertSupabasePost } from '../lib/cms';
import { supabase } from '../lib/supabase';
import Seo from '../components/Seo';

function categoryFallback(category:string){const c=(category||'').toLowerCase();if(c.includes('ai')||c.includes('tech'))return siteConfig.heroDesktop;if(c.includes('osint')||c.includes('research'))return siteConfig.brandWide;if(c.includes('digital safety')||c.includes('security')||c.includes('cyber'))return siteConfig.heroMobile;if(c.includes('course')||c.includes('learn')||c.includes('event'))return siteConfig.brandWide;return siteConfig.heroDesktop}
const blank=():AdminPost=>({id:'',title:'',summary:'',source:'NexVibe',sourceUrl:'',publishedAt:new Date().toISOString().slice(0,10),category:'Cybersecurity News',official:false,image:'',tags:[],content:[''],language:'en',status:'draft',featured:false,country:'',verificationStatus:'unverified'});
function slugify(s:string){return s.toLowerCase().trim().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'').slice(0,80)||`post-${Date.now()}`}
function sameStory(a:AdminPost,b:NewsItem){const au=(a.sourceUrl||'').replace(/\/$/,'');const bu=(b.sourceUrl||'').replace(/\/$/,'');if(au&&bu&&au===bu)return true;return a.title.toLowerCase().replace(/\W/g,'')===b.title.toLowerCase().replace(/\W/g,'')}

export default function Admin(){
  const nav=useNavigate();const {data:live}=useLiveNews();const [tab,setTab]=useState<'overview'|'posts'|'editor'|'imports'|'tools'|'media'|'settings'>('overview');const [posts,setPosts]=useState<AdminPost[]>(getLocalAdminPosts);const [draft,setDraft]=useState<AdminPost>(blank());const [msg,setMsg]=useState('');const [toast,setToast]=useState('');const [uploading,setUploading]=useState(false);const [saving,setSaving]=useState(false);const [postFilter,setPostFilter]=useState('all');const [postQ,setPostQ]=useState('');
  function notice(text:string){setMsg(text);setToast(text);window.setTimeout(()=>setToast(''),3500)}
  useEffect(()=>{if(!featureFlags.SUPABASE_ENABLED){if(sessionStorage.getItem('nexvibe-admin-demo')!=='1')nav('/login');return;}let alive=true;(async()=>{const {data:{user}}=await supabase!.auth.getUser();if(!alive)return;if(!user){nav('/login');return;}const {data:roles}=await supabase!.from('user_roles').select('role').eq('user_id',user.id);const allowed=(roles||[]).some((r:any)=>r.role==='editor'||r.role==='administrator');if(!allowed){notice('This account does not have Editor or Administrator permission.');setTab('overview');return;}const remote=await fetchSupabaseAdminPosts();if(alive&&remote.length)setPosts(remote)})();return()=>{alive=false}},[nav]);
  const combined=useMemo(()=>[...posts,...manualPosts.map(p=>({...p,status:'published' as const,featured:false}))],[posts]);
  const visiblePosts=useMemo(()=>combined.filter(p=>(postFilter==='all'||p.status===postFilter)&&(!postQ||`${p.title} ${p.category} ${p.source}`.toLowerCase().includes(postQ.toLowerCase()))),[combined,postFilter,postQ]);
  function persist(next:AdminPost[]){setPosts(next);saveLocalAdminPosts(next)}
  function edit(p:AdminPost){setDraft({...p,content:[...(p.content||[''])]});setTab('editor');setMsg('')}
  async function uploadCover(file?:File){if(!file)return;if(!featureFlags.SUPABASE_ENABLED||!supabase){notice('Supabase Storage is required for direct image uploads.');return;}if(!file.type.startsWith('image/')){notice('Please choose an image file.');return;}if(file.size>8*1024*1024){notice('Image is too large. Maximum cover image size is 8 MB.');return;}setUploading(true);notice('Uploading cover image…');try{const rawExt=(file.name.split('.').pop()||'jpg').toLowerCase();const ext=['jpg','jpeg','png','webp','gif'].includes(rawExt)?rawExt:'jpg';const folder=new Date().toISOString().slice(0,10);const filename=`${slugify(draft.title||'nexvibe-post')}-${Date.now()}.${ext}`;const path=`${folder}/${filename}`;const {data,error}=await supabase.storage.from('post-images').upload(path,file,{cacheControl:'31536000',upsert:false,contentType:file.type});if(error)throw error;const {data:pub}=supabase.storage.from('post-images').getPublicUrl(data.path);setDraft(d=>({...d,image:pub.publicUrl}));notice('Cover image uploaded for this post.')}catch(err:any){notice(`Image upload failed: ${err?.message||'Unknown error'}`)}finally{setUploading(false)}}
  async function submit(e:React.FormEvent){e.preventDefault();if(draft.status==='scheduled'&&!draft.scheduledAt){notice('Choose a scheduled publish date and time first.');return;}setSaving(true);const p:AdminPost={...draft,id:draft.id||slugify(draft.title),source:'NexVibe',image:draft.image||categoryFallback(draft.category),tags:draft.tags||[],sourceVerifiedAt:draft.verificationStatus==='verified'?(draft.sourceVerifiedAt||new Date().toISOString()):undefined};const next=posts.some(x=>x.id===p.id)?posts.map(x=>x.id===p.id?p:x):[p,...posts];persist(next);setDraft(p);if(featureFlags.SUPABASE_ENABLED){const r=await upsertSupabasePost(p);notice(r.ok?(p.status==='published'?'Published successfully ✅':p.status==='scheduled'?'Scheduled successfully ✅':'Draft saved ✅'):`Supabase save failed: ${r.error}`)}else notice('Saved locally in this browser.');setSaving(false)}
  async function removePost(p:AdminPost){if(!confirm(`Delete “${p.title}”? This cannot be undone.`))return;if(featureFlags.SUPABASE_ENABLED){const r=await deleteSupabasePost(p.id);if(!r.ok){notice(`Supabase delete failed: ${r.error}`);return;}}persist(posts.filter(x=>x.id!==p.id));notice('Post deleted.')} 
  function importLive(item:NewsItem){if(posts.some(p=>sameStory(p,item))){notice('Duplicate detected — this source/story is already in the editorial queue.');return;}const p:AdminPost={...item,id:`draft-${item.source.toLowerCase().replace(/[^a-z]+/g,'-')}-${item.id}`,status:'draft',featured:false,verificationStatus:item.official?'verified':'pending',sourceVerifiedAt:item.official?new Date().toISOString():undefined,content:[`Imported official-source item from ${item.source}. Review the source, write an original NexVibe summary, add user/admin actions, and only then publish.`]};persist([p,...posts]);notice(`Imported “${p.title}” as a verified-source draft.`)}
  function exportJson(){const blob=new Blob([JSON.stringify(posts,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='nexvibe-posts-export.json';a.click();URL.revokeObjectURL(a.href)}
  function importJson(file?:File){if(!file)return;file.text().then(t=>{try{const arr=JSON.parse(t);if(!Array.isArray(arr))throw 0;persist(arr);notice(`Imported ${arr.length} posts into this browser.`)}catch{notice('Could not import JSON file.')}})}
  const stats={total:combined.length,published:combined.filter(p=>p.status==='published').length,drafts:posts.filter(p=>p.status==='draft').length,scheduled:posts.filter(p=>p.status==='scheduled').length,live:(live.items||[]).length};const coverPreview=draft.image||categoryFallback(draft.category);
  return <><Seo title="Admin Studio" path="/admin"/><PageHero eyebrow="Admin" title="NexVibe Content Studio" lead="Mobile-first, role-protected publishing with source verification, scheduled posts and direct cover image uploads."/><section className="nv-section-compact"><div className="nv-container nv-admin-layout">
    <aside className="nv-card nv-admin-sidebar">{[['overview','Overview',Newspaper],['posts','Posts',Newspaper],['editor','New / Edit',FilePlus2],['imports','Import Official Feed',RefreshCw],['tools','Tools',Wrench],['media','Media',Image],['settings','Settings',Settings]].map(([id,label,Icon]:any)=><button key={id} className={tab===id?'active':''} onClick={()=>setTab(id)}><Icon size={17}/>{label}</button>)}<button onClick={()=>{sessionStorage.removeItem('nexvibe-admin-demo');supabase?.auth.signOut();nav('/')}}><LogOut size={17}/>Logout</button></aside>
    <div className="nv-admin-main">{msg&&<div className="nv-card nv-admin-message">{msg}</div>}
      {tab==='overview'&&<><div className="nv-stats"><div className="nv-card nv-stat"><strong>{stats.total}</strong><span>Total items</span></div><div className="nv-card nv-stat"><strong>{stats.published}</strong><span>Published</span></div><div className="nv-card nv-stat"><strong>{stats.drafts}</strong><span>Drafts</span></div><div className="nv-card nv-stat"><strong>{stats.scheduled}</strong><span>Scheduled</span></div></div><div className="nv-card nv-admin-overview"><h3>Publishing architecture</h3><p className="nv-muted">Supabase publishing and image storage are connected. Scheduled articles become public automatically once their scheduled time is reached. Imported official feeds are deduplicated and remain drafts until review.</p><div className="nv-meta"><span className="nv-chip">Supabase: {featureFlags.SUPABASE_ENABLED?'Configured':'Not configured'}</span><span className="nv-chip">Post images: Enabled</span><span className="nv-chip">Official feed: {stats.live}</span></div></div></>}
      {tab==='posts'&&<><div className="nv-filter-panel nv-card"><input className="nv-input" placeholder="Search editorial posts…" value={postQ} onChange={e=>setPostQ(e.target.value)}/><select className="nv-input" value={postFilter} onChange={e=>setPostFilter(e.target.value)}><option value="all">All statuses</option><option value="draft">Drafts</option><option value="published">Published</option><option value="scheduled">Scheduled</option><option value="archived">Archived</option></select><span className="nv-result-count">{visiblePosts.length}</span></div><div className="nv-admin-list">{visiblePosts.map(p=><article key={p.id} className="nv-card nv-admin-item"><img src={p.image||categoryFallback(p.category)} alt=""/><div><div className="nv-meta"><span className="nv-chip">{p.category}</span><span>{p.status}</span>{p.verificationStatus==='verified'&&<span className="nv-live-badge">Verified source</span>}{p.status==='scheduled'&&<span><Clock3 size={12}/> {p.scheduledAt?new Date(p.scheduledAt).toLocaleString():'Time missing'}</span>}</div><h3>{p.title}</h3><p className="nv-muted nv-clamp-2">{p.summary}</p></div><div className="nv-admin-actions">{p.source==='NexVibe'&&posts.some(x=>x.id===p.id)&&<><button className="nv-button" onClick={()=>edit(p as AdminPost)}>Edit</button><button className="nv-button nv-button-danger" onClick={()=>removePost(p as AdminPost)}><Trash2 size={14}/>Delete</button></>}</div></article>)}</div></>}
      {tab==='editor'&&<form className="nv-card nv-form nv-editor-card" onSubmit={submit}><div className="nv-form-grid">
        <div className="nv-field nv-span-2"><label>Title</label><input className="nv-input" value={draft.title} onChange={e=>setDraft(d=>({...d,title:e.target.value}))} required/></div>
        <div className="nv-field"><label>Category</label><input className="nv-input" value={draft.category} onChange={e=>setDraft(d=>({...d,category:e.target.value}))}/></div><div className="nv-field"><label>Country / region</label><input className="nv-input" value={draft.country||''} onChange={e=>setDraft(d=>({...d,country:e.target.value}))} placeholder="Sri Lanka, Global…"/></div>
        <div className="nv-field"><label>Language</label><select className="nv-input" value={draft.language||'en'} onChange={e=>setDraft(d=>({...d,language:e.target.value as any}))}><option value="en">English</option><option value="si">Sinhala</option></select></div><div className="nv-field"><label>Article date</label><input className="nv-input" type="date" value={draft.publishedAt} onChange={e=>setDraft(d=>({...d,publishedAt:e.target.value}))}/></div>
        <div className="nv-field"><label>Status</label><select className="nv-input" value={draft.status} onChange={e=>setDraft(d=>({...d,status:e.target.value as any}))}><option value="draft">Draft</option><option value="published">Published</option><option value="scheduled">Scheduled</option><option value="archived">Archived</option></select></div>{draft.status==='scheduled'&&<div className="nv-field"><label>Publish automatically at</label><input className="nv-input" type="datetime-local" value={draft.scheduledAt?draft.scheduledAt.slice(0,16):''} onChange={e=>setDraft(d=>({...d,scheduledAt:e.target.value?new Date(e.target.value).toISOString():undefined}))} required/></div>}
        <div className="nv-field nv-span-2"><label>Summary</label><textarea className="nv-input" value={draft.summary} onChange={e=>setDraft(d=>({...d,summary:e.target.value}))}/></div><div className="nv-field nv-span-2"><label>Tags (comma separated)</label><input className="nv-input" value={(draft.tags||[]).join(', ')} onChange={e=>setDraft(d=>({...d,tags:e.target.value.split(',').map(x=>x.trim()).filter(Boolean)}))}/></div>
        <div className="nv-field nv-span-2"><label>Post cover image</label><div className="nv-upload-row"><input className="nv-input" placeholder="Image URL — or upload from your phone" value={draft.image||''} onChange={e=>setDraft(d=>({...d,image:e.target.value}))}/><label className="nv-button nv-button-primary"><Upload size={16}/>{uploading?'Uploading…':'Upload image'}<input type="file" accept="image/jpeg,image/png,image/webp,image/gif" hidden disabled={uploading} onChange={e=>{uploadCover(e.target.files?.[0]);e.currentTarget.value=''}}/></label></div><p className="nv-muted">JPG, PNG, WebP or GIF, max 8 MB. Each post keeps its own cover; empty uses a category fallback.</p><div className="nv-cover-preview"><img src={coverPreview} alt="Cover preview"/>{draft.image&&<button type="button" className="nv-button" onClick={()=>setDraft(d=>({...d,image:''}))}><X size={15}/>Use fallback</button>}</div></div>
        <div className="nv-field nv-span-2"><label>Article body (paragraphs separated by blank line)</label><textarea className="nv-input" style={{minHeight:320}} value={(draft.content||[]).join('\n\n')} onChange={e=>setDraft(d=>({...d,content:e.target.value.split(/\n\s*\n/)}))}/></div>
        <div className="nv-field nv-span-2"><label>Source URL</label><input className="nv-input" value={draft.sourceUrl||''} onChange={e=>setDraft(d=>({...d,sourceUrl:e.target.value}))}/></div><div className="nv-field"><label>Source verification</label><select className="nv-input" value={draft.verificationStatus||'unverified'} onChange={e=>setDraft(d=>({...d,verificationStatus:e.target.value as any,sourceVerifiedAt:e.target.value==='verified'?new Date().toISOString():undefined}))}><option value="unverified">Unverified</option><option value="pending">Pending review</option><option value="verified">Verified</option></select></div><div className="nv-field"><label>Official source?</label><select className="nv-input" value={draft.official?'yes':'no'} onChange={e=>setDraft(d=>({...d,official:e.target.value==='yes'}))}><option value="no">No</option><option value="yes">Yes</option></select></div>
      </div><div className="nv-sticky-actions"><button type="button" className="nv-button" onClick={()=>setDraft(blank())}>New</button><button className="nv-button nv-button-primary" type="submit" disabled={uploading||saving}><Save size={16}/>{saving?'Saving…':draft.status==='published'?'Publish now':draft.status==='scheduled'?'Schedule':'Save draft'}</button></div></form>}
      {tab==='imports'&&<><div className="nv-card nv-admin-overview"><h3>Official-feed workflow</h3><p className="nv-muted">Fetch → deduplicate by original URL/title → mark official-source verification → import as Draft → admin review → publish or schedule.</p></div><div className="nv-admin-list">{(live.items||[]).map(i=>{const duplicate=posts.some(p=>sameStory(p,i));return <article key={`${i.source}-${i.id}`} className="nv-card nv-list-card"><span className="nv-live-badge"><CheckCircle2 size={13}/>Official external feed</span><h3>{i.title}</h3><p>{i.summary}</p><div className="nv-card-footer"><a className="nv-button" href={i.sourceUrl} target="_blank" rel="noreferrer">Verify source</a><button className="nv-button nv-button-primary" disabled={duplicate} onClick={()=>importLive(i)}>{duplicate?'Already imported':'Import as Draft'}</button></div></article>})}</div></>}
      {tab==='tools'&&<div className="nv-grid-2">{toolDirectory.slice(0,8).map(t=><article key={t.id} className="nv-card nv-list-card"><span className="nv-chip">{t.category}</span><h3>{t.name}</h3><p>{t.description}</p><div className="nv-meta"><span>{t.classification}</span><span>Verified {t.lastVerified}</span></div></article>)}</div>}
      {tab==='media'&&<><div className="nv-card nv-admin-overview"><h3>Post image storage</h3><p className="nv-muted">Direct covers go to the Supabase <strong>post-images</strong> bucket. Public reading is enabled; uploads and changes are restricted to editors and administrators.</p></div><div className="nv-grid-3">{[{src:siteConfig.logo,n:'Official logo'},{src:siteConfig.heroDesktop,n:'Desktop hero fallback'},{src:siteConfig.heroMobile,n:'Cyber / safety fallback'},{src:siteConfig.brandWide,n:'OSINT / learning fallback'}].map(x=><div className="nv-card" key={x.n} style={{overflow:'hidden'}}><img src={x.src} alt={x.n} style={{display:'block',width:'100%',aspectRatio:'16/10',objectFit:'cover'}}/><div style={{padding:14}}><strong>{x.n}</strong></div></div>)}</div></>}
      {tab==='settings'&&<div className="nv-card nv-admin-overview"><h3>Contact & feature settings</h3><p><strong>Email:</strong> {siteConfig.email}</p><p><strong>Facebook:</strong> configured</p><p><strong>TikTok:</strong> @nexvibeofficial</p><div className="nv-meta"><span className="nv-chip">Post images: enabled</span><span className="nv-chip">Scheduled publishing: enabled</span><span className="nv-chip">Duplicate checks: enabled</span><span className="nv-chip">Payments: disabled</span></div><div className="nv-report-actions"><button className="nv-button" onClick={exportJson}><Download size={15}/>Export posts JSON</button><label className="nv-button"><Upload size={15}/>Import posts JSON<input type="file" accept="application/json" hidden onChange={e=>importJson(e.target.files?.[0])}/></label></div></div>}
    </div></div></section>{toast&&<div className="nv-toast"><CheckCircle2 size={18}/>{toast}</div>}</>
}
