import { useEffect, useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { LogOut, Save, Star, GraduationCap } from 'lucide-react';
import { PageHero } from '../components/Common';
import { featureFlags, siteConfig } from '../lib/config';
import { supabase } from '../lib/supabase';
import { getProfile, listBookmarks, listProgress, updateProfile } from '../lib/account';
import Seo from '../components/Seo';

export function Login(){const [email,setEmail]=useState('');const [password,setPassword]=useState('');const [msg,setMsg]=useState('');const [busy,setBusy]=useState(false);const navigate=useNavigate();async function submit(e:React.FormEvent){e.preventDefault();if(!supabase){setMsg('Supabase is not configured yet.');return;}setBusy(true);const {error}=await supabase.auth.signInWithPassword({email,password});setBusy(false);if(error)setMsg(error.message);else navigate('/admin')}return <><Seo title="Sign In" path="/login"/><PageHero eyebrow="Sign In" title="NexVibe account access" lead="Sign in to sync bookmarks, learning progress and access role-protected publishing tools."/><section className="nv-section-compact"><div className="nv-container nv-auth-card nv-card"><img src={siteConfig.logo} alt="NexVibe logo" style={{width:76,height:76,borderRadius:'50%',display:'block',margin:'0 auto 18px'}}/><form className="nv-form" onSubmit={submit}><div className="nv-field"><label>Email</label><input className="nv-input" type="email" value={email} onChange={e=>setEmail(e.target.value)} autoComplete="email" required/></div><div className="nv-field"><label>Password</label><input className="nv-input" type="password" value={password} onChange={e=>setPassword(e.target.value)} autoComplete="current-password" required/></div><button className="nv-button nv-button-primary" type="submit" disabled={busy}>{busy?'Signing in…':'Sign In'}</button>{!featureFlags.SUPABASE_ENABLED&&<button type="button" className="nv-button" onClick={()=>{sessionStorage.setItem('nexvibe-admin-demo','1');navigate('/admin')}}>Open local Admin Demo</button>}<p className="nv-muted" style={{margin:0}}>{msg}</p><p className="nv-muted">No account? <Link to="/register" style={{color:'var(--cyan)'}}>Register</Link></p></form></div></section></>}

export function Register(){const [email,setEmail]=useState('');const [password,setPassword]=useState('');const [msg,setMsg]=useState('');const [busy,setBusy]=useState(false);async function submit(e:React.FormEvent){e.preventDefault();if(!supabase){setMsg('Supabase is not configured in this deployment.');return;}setBusy(true);const redirectTo='https://nexvibedigital.github.io/nexvibe-digital-hub/';const {error}=await supabase.auth.signUp({email,password,options:{emailRedirectTo:redirectTo}});setBusy(false);setMsg(error?error.message:'Check your email to confirm the account.')}return <><Seo title="Register" path="/register"/><PageHero eyebrow="Register" title="Create a NexVibe account" lead="Accounts sync bookmarks, learning progress and profile preferences across your devices."/><section className="nv-section-compact"><form className="nv-container nv-auth-card nv-card nv-form" onSubmit={submit}><div className="nv-field"><label>Email</label><input className="nv-input" type="email" value={email} onChange={e=>setEmail(e.target.value)} required/></div><div className="nv-field"><label>Password</label><input className="nv-input" minLength={12} type="password" value={password} onChange={e=>setPassword(e.target.value)} required/><small className="nv-muted">Use 12+ characters and a unique password.</small></div><button className="nv-button nv-button-primary" disabled={busy}>{busy?'Creating account…':'Register'}</button><p className="nv-muted">{msg}</p></form></section></>}

export function Profile(){
  const [user,setUser]=useState<any>(null);const [displayName,setDisplayName]=useState('');const [language,setLanguage]=useState('en');const [msg,setMsg]=useState('');const [saved,setSaved]=useState(0);const [progress,setProgressCount]=useState(0);const navigate=useNavigate();
  useEffect(()=>{(async()=>{const {user,profile}=await getProfile();setUser(user);setDisplayName(profile?.display_name||'');setLanguage(profile?.language||'en');setSaved((await listBookmarks()).length);setProgressCount((await listProgress()).filter(x=>x.completed).length)})()},[]);
  async function save(){const r=await updateProfile({display_name:displayName,language});setMsg(r.ok?'Profile saved.':r.error)}
  async function logout(){await supabase?.auth.signOut();navigate('/')}
  return <><Seo title="Profile" path="/profile"/><PageHero eyebrow="Profile" title="Your NexVibe profile" lead="Manage your display name and see synced bookmarks and learning progress."/><section className="nv-section-compact"><div className="nv-container">{user?<div className="nv-profile-grid"><div className="nv-card" style={{padding:22}}><div className="nv-profile-avatar">{(displayName||user.email||'N').slice(0,1).toUpperCase()}</div><h2>{displayName||'NexVibe member'}</h2><p className="nv-muted">{user.email}</p><div className="nv-stats"><div className="nv-card nv-stat"><Star/><strong>{saved}</strong><span>Saved</span></div><div className="nv-card nv-stat"><GraduationCap/><strong>{progress}</strong><span>Lessons complete</span></div></div></div><div className="nv-card nv-form" style={{padding:22}}><div className="nv-field"><label>Display name</label><input className="nv-input" value={displayName} onChange={e=>setDisplayName(e.target.value)} placeholder="Your display name"/></div><div className="nv-field"><label>Preferred language</label><select className="nv-input" value={language} onChange={e=>setLanguage(e.target.value)}><option value="en">English</option><option value="si">Sinhala</option><option value="ta">Tamil</option></select></div><button className="nv-button nv-button-primary" onClick={save}><Save size={16}/>Save profile</button><button className="nv-button" onClick={logout}><LogOut size={16}/>Sign out</button>{msg&&<p className="nv-muted">{msg}</p>}</div></div>:<div className="nv-card" style={{padding:24}}><h2>Sign in to sync your NexVibe activity</h2><p className="nv-muted">Bookmarks and lesson progress can work locally without an account, but signing in keeps them available across devices.</p><Link className="nv-button nv-button-primary" to="/login">Sign in</Link></div>}</div></section></>}
