import { useEffect, useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { PageHero } from '../components/Common';
import { featureFlags, siteConfig } from '../lib/config';
import { supabase } from '../lib/supabase';

export function Login(){const [email,setEmail]=useState('');const [password,setPassword]=useState('');const [msg,setMsg]=useState('');const navigate=useNavigate();async function submit(e:React.FormEvent){e.preventDefault();if(!supabase){setMsg('Supabase is not configured yet. Use the local Admin Demo button for this static GitHub Pages build.');return;}const {error}=await supabase.auth.signInWithPassword({email,password});if(error)setMsg(error.message);else navigate('/admin')}return <><PageHero eyebrow="Sign In" title="NexVibe account access" lead="Supabase free-tier authentication becomes active after environment variables and database policies are configured."/><section className="nv-section-compact"><div className="nv-container nv-auth-card nv-card"><img src={siteConfig.logo} alt="NexVibe logo" style={{width:76,height:76,borderRadius:'50%',display:'block',margin:'0 auto 18px'}}/><form className="nv-form" onSubmit={submit}><div className="nv-field"><label>Email</label><input className="nv-input" type="email" value={email} onChange={e=>setEmail(e.target.value)} required/></div><div className="nv-field"><label>Password</label><input className="nv-input" type="password" value={password} onChange={e=>setPassword(e.target.value)} required/></div><button className="nv-button nv-button-primary" type="submit">Sign In</button>{!featureFlags.SUPABASE_ENABLED&&<button type="button" className="nv-button" onClick={()=>{sessionStorage.setItem('nexvibe-admin-demo','1');navigate('/admin')}}>Open local Admin Demo</button>}<p className="nv-muted" style={{margin:0}}>{msg}</p><p className="nv-muted">No account? <Link to="/register" style={{color:'var(--cyan)'}}>Register</Link></p></form></div></section></>}

export function Register(){const [email,setEmail]=useState('');const [password,setPassword]=useState('');const [msg,setMsg]=useState('');async function submit(e:React.FormEvent){e.preventDefault();if(!supabase){setMsg('Supabase is not configured in this deployment. See README to enable free-tier accounts.');return;}const {error}=await supabase.auth.signUp({email,password});setMsg(error?error.message:'Check your email to confirm the account if email confirmation is enabled.')}return <><PageHero eyebrow="Register" title="Create a NexVibe account" lead="Accounts can save bookmarks, learning progress and submissions when Supabase is enabled."/><section className="nv-section-compact"><form className="nv-container nv-auth-card nv-card nv-form" onSubmit={submit}><div className="nv-field"><label>Email</label><input className="nv-input" type="email" value={email} onChange={e=>setEmail(e.target.value)} required/></div><div className="nv-field"><label>Password</label><input className="nv-input" minLength={10} type="password" value={password} onChange={e=>setPassword(e.target.value)} required/></div><button className="nv-button nv-button-primary">Register</button><p className="nv-muted">{msg}</p></form></section></>}

export function Profile(){const [user,setUser]=useState<any>(null);useEffect(()=>{supabase?.auth.getUser().then(({data})=>setUser(data.user))},[]);return <><PageHero eyebrow="Profile" title="Your NexVibe profile" lead="Profile, bookmarks, learning progress and notification preferences use Supabase when configured."/><section className="nv-section-compact"><div className="nv-container nv-card" style={{padding:22}}>{user?<><h3>{user.email}</h3><p className="nv-muted">Authenticated Supabase user.</p></>:<p className="nv-muted">No authenticated Supabase session in this build.</p>}</div></section></>}
