import { useEffect, useMemo, useRef, useState, type ReactNode } from 'react';
import { Link, useLocation } from 'react-router-dom';
import { Copy, Download, ExternalLink, Eye, EyeOff, FileKey2, Globe2, KeyRound, Link2, MailCheck, QrCode, ShieldCheck, Smartphone, Trash2 } from 'lucide-react';
import jsQR from 'jsqr';
import SparkMD5 from 'spark-md5';
import { PageHero } from '../components/Common';
import { analyseUrlLocal, maskEmail, passwordStrength, shaHex } from '../lib/security';
import { generateNexVibePdf } from '../lib/pdf';

function ToolShell({id,icon,title,kicker,children}:{id:string;icon:ReactNode;title:string;kicker:string;children:ReactNode}){
  return <section id={id} className="nv-tool-panel nv-card" style={{scrollMarginTop:100}}><div className="nv-meta"><span className="nv-chip">{kicker}</span></div><div style={{display:'flex',gap:10,alignItems:'center',marginTop:10,color:'var(--cyan)'}}>{icon}<h2 style={{color:'white',margin:0}}>{title}</h2></div>{children}</section>
}

function PasswordChecker(){
  const [value,setValue]=useState(''); const [show,setShow]=useState(false); const [result,setResult]=useState<{found:boolean;count:number}|null>(null); const [state,setState]=useState('');
  const strength=useMemo(()=>passwordStrength(value),[value]);
  async function check(){if(!value)return;setState('Checking…');setResult(null);try{const hash=await shaHex('SHA-1',value);const prefix=hash.slice(0,5),suffix=hash.slice(5);const r=await fetch(`https://api.pwnedpasswords.com/range/${prefix}`,{headers:{'Add-Padding':'true'}});if(!r.ok)throw new Error('lookup failed');const text=await r.text();const line=text.split(/\r?\n/).find(l=>l.startsWith(suffix+':'));const count=line?Number(line.split(':')[1]):0;setResult({found:count>0,count});setState('');}catch{setState('Unable to verify right now. Try again later.');}finally{setValue('')}}
  return <ToolShell id="password-check" kicker="Free • Local-first" icon={<KeyRound/>} title="Password Exposure Checker"><p>Your password is hashed locally. Only the first five SHA-1 hash characters are sent to the official HIBP Pwned Passwords range API, and matching happens locally.</p><div className="nv-card" style={{padding:12,background:'#07111f'}}><strong>Privacy warning</strong><p className="nv-muted" style={{marginBottom:0}}>Never enter the real password of a highly sensitive account if you do not trust the device you are using. NexVibe does not store or transmit your full password.</p></div><div className="nv-form" style={{marginTop:14}}><div style={{display:'grid',gridTemplateColumns:'1fr auto',gap:8}}><input className="nv-input" type={show?'text':'password'} value={value} onChange={e=>setValue(e.target.value)} placeholder="Enter a password to check" autoComplete="new-password"/><button className="nv-button" onClick={()=>setShow(v=>!v)} aria-label="Show or hide password">{show?<EyeOff/>:<Eye/>}</button></div>{value&&<div><div className="nv-card-footer"><span>Strength: <strong>{strength.label}</strong></span><span>{strength.pct}%</span></div><div className="nv-progress"><span style={{width:`${strength.pct}%`}}/></div>{strength.notes.map(n=><small key={n} className="nv-muted" style={{display:'block',marginTop:4}}>{n}</small>)}</div>}<button className="nv-button nv-button-primary" type="button" onClick={check}>Check known breach-password data</button></div>{state&&<div className="nv-result"><span className="nv-status-warn">{state}</span></div>}{result&&<div className="nv-result"><h4 className={result.found?'nv-status-high':'nv-status-low'}>{result.found?'High-risk indicator':'No known issue found by this check'}</h4><p>{result.found?`This password hash appeared approximately ${result.count.toLocaleString()} times in the HIBP Pwned Passwords dataset. Do not use it.`:'No matching hash suffix was returned. This does not prove the password or account is safe.'}</p><ul><li>Use a unique password for every important account.</li><li>Use a reputable password manager.</li><li>Enable multi-factor authentication.</li></ul><button className="nv-button" onClick={()=>generateNexVibePdf({title:'Password Exposure Report',type:'Password Exposure Report',summary:result.found?'Password exposure indicator was found.':'No known issue was found by this check.',findings:[result.found?`Approximate breach-password appearance count: ${result.count}.`:'No matching Pwned Passwords suffix was returned.'],actions:['Change exposed or reused credentials.','Use a password manager to generate unique credentials.','Enable MFA.']})}><Download size={15}/>PDF report</button></div>}</ToolShell>
}

function EmailSafety(){
  const [email,setEmail]=useState(''); const [external,setExternal]=useState<'none'|'breaches'|'unchecked'>('unchecked'); const [data,setData]=useState<string[]>([]); const [habits,setHabits]=useState<Record<string,boolean>>({});
  const items=['Unique email password','MFA enabled','Recovery methods reviewed','Login activity checked recently','Phishing links are independently verified']; const exposed=['Email','Password','Phone number','Name','Address','Date of birth','Security questions','Other personal data'];
  const habitScore=items.filter(x=>habits[x]).length; const findings:string[]=[]; if(external==='breaches')findings.push(`User confirmed one or more breaches externally; exposed data selected: ${data.join(', ')||'not specified'}.`);if(external==='none')findings.push('User confirmed no breaches were shown during their external check.');if(external==='unchecked')findings.push('External breach check not completed.');
  const actions=[external==='breaches'?'Change affected passwords and secure exposed accounts immediately.':'Keep unique credentials and MFA enabled.',habitScore<5?'Complete the missing email-security habits shown in this assessment.':'Continue monitoring account security and recovery options.','Be alert for targeted phishing using exposed personal information.'];
  return <ToolShell id="email-safety" kicker="Free • User-confirmed" icon={<MailCheck/>} title="Free Email Safety Assessment"><p>Automatic email-breach retrieval requires a paid provider and is disabled. This free flow keeps your email in browser state only and lets you verify it yourself on the official HIBP website.</p><div className="nv-form"><input className="nv-input" type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="Your email (optional — not saved)"/>{email&&<span className="nv-muted">Report display: <strong>{maskEmail(email)}</strong></span>}<a className="nv-button" href="https://haveibeenpwned.com/" target="_blank" rel="noreferrer">Open official Have I Been Pwned <ExternalLink size={15}/></a><small className="nv-muted">NexVibe does not put your email in the external URL.</small><div className="nv-field"><label>What did the official external check show?</label><select className="nv-input" value={external} onChange={e=>setExternal(e.target.value as any)}><option value="unchecked">Not checked</option><option value="none">No breaches shown</option><option value="breaches">One or more breaches shown</option></select></div>{external==='breaches'&&<div className="nv-checklist">{exposed.map(x=><label key={x} className="nv-checkitem"><input type="checkbox" checked={data.includes(x)} onChange={e=>setData(d=>e.target.checked?[...d,x]:d.filter(y=>y!==x))}/><span>{x}</span></label>)}</div>}<h3 style={{marginBottom:0}}>Security habits</h3><div className="nv-checklist">{items.map(x=><label key={x} className="nv-checkitem"><input type="checkbox" checked={!!habits[x]} onChange={e=>setHabits(h=>({...h,[x]:e.target.checked}))}/><span>{x}</span></label>)}</div></div><div className="nv-result"><h4 className={external==='breaches'||habitScore<3?'nv-status-warn':'nv-status-low'}>{external==='breaches'?'Multiple warning signs':habitScore<3?'Possible warning':'No known issue found by this assessment'}</h4><p>Habit score: {habitScore}/5. User-confirmed external check—not independently verified by NexVibe.</p><div className="nv-report-actions"><button className="nv-button nv-button-primary" onClick={()=>generateNexVibePdf({title:'Free Email Safety Assessment',type:'Digital Safety Assessment',maskedEmail:maskEmail(email),summary:`Email safety habit score ${habitScore}/5. External HIBP check: ${external}.`,findings,actions})}><Download size={15}/>Generate PDF</button><button className="nv-button" onClick={()=>{setEmail('');setData([]);setExternal('unchecked');setHabits({})}}><Trash2 size={15}/>Delete local form data</button></div></div></ToolShell>
}

function UrlChecker(){const [url,setUrl]=useState('');const [analysis,setAnalysis]=useState<ReturnType<typeof analyseUrlLocal>|null>(null);return <ToolShell id="url-check" kicker="Free • Local analysis" icon={<Link2/>} title="Suspicious URL Analyser"><p>This tool checks visible warning signs locally. It does not automatically open the URL and does not fetch page content in your browser.</p><div className="nv-form"><input className="nv-input" value={url} onChange={e=>setUrl(e.target.value)} placeholder="https://example.com/path"/><button className="nv-button nv-button-primary" onClick={()=>setAnalysis(analyseUrlLocal(url))}>Analyse visible warning signs</button></div>{analysis&&<div className="nv-result"><h4 className={analysis.tone==='high'?'nv-status-high':analysis.tone==='warn'?'nv-status-warn':'nv-status-low'}>{analysis.label}</h4><ul>{analysis.findings.map(f=><li key={f}>{f}</li>)}</ul><p><strong>This local analysis cannot guarantee that a URL is safe.</strong></p><button className="nv-button" onClick={()=>generateNexVibePdf({title:'URL Warning-Signs Report',type:'URL Warning-Signs Report',summary:analysis.label,findings:analysis.findings,actions:['Verify the exact domain independently.','Do not enter credentials or payment data if anything looks unusual.','Use an independent reputation service for higher-confidence checks.']})}><Download size={15}/>PDF report</button></div>}</ToolShell>}

function QrChecker(){const [text,setText]=useState('');const [analysis,setAnalysis]=useState<ReturnType<typeof analyseUrlLocal>|null>(null);async function scan(file?:File){if(!file)return;const img=await createImageBitmap(file);const c=document.createElement('canvas');c.width=img.width;c.height=img.height;const ctx=c.getContext('2d')!;ctx.drawImage(img,0,0);const d=ctx.getImageData(0,0,c.width,c.height);const code=jsQR(d.data,d.width,d.height);const val=code?.data||'';setText(val);setAnalysis(val&&/^(https?:\/\/|www\.)/i.test(val)?analyseUrlLocal(val):null)}return <ToolShell id="qr-check" kicker="Free • Local decode" icon={<QrCode/>} title="QR Code Safety Scanner"><p>Upload a QR image or capture one with your phone camera. The image stays in the browser unless you choose to save it elsewhere.</p><input className="nv-input" type="file" accept="image/*" capture="environment" onChange={e=>scan(e.target.files?.[0])}/>{text?<div className="nv-result"><h4>Extracted content</h4><p className="nv-code">{text}</p><div className="nv-report-actions"><button className="nv-button" onClick={()=>navigator.clipboard.writeText(text)}><Copy size={15}/>Copy</button>{/^https?:\/\//i.test(text)&&<a className="nv-button nv-button-danger" href={text} target="_blank" rel="noreferrer" onClick={e=>{if(!confirm('Open this QR destination in a new tab? Verify the URL first.'))e.preventDefault()}}>Open only after confirmation <ExternalLink size={15}/></a>}</div>{analysis&&<><h4 className={analysis.tone==='high'?'nv-status-high':analysis.tone==='warn'?'nv-status-warn':'nv-status-low'}>{analysis.label}</h4><ul>{analysis.findings.map(f=><li key={f}>{f}</li>)}</ul></>}</div>:<div className="nv-result nv-muted">No QR content decoded yet.</div>}</ToolShell>}

function FileHash(){const [file,setFile]=useState<File|null>(null);const [hashes,setHashes]=useState<{sha256:string;sha1:string;md5:string}|null>(null);async function run(){if(!file)return;const buf=await file.arrayBuffer();const sha256=await shaHex('SHA-256',buf),sha1=await shaHex('SHA-1',buf),md5=SparkMD5.ArrayBuffer.hash(buf).toUpperCase();setHashes({sha256,sha1,md5})}return <ToolShell id="file-hash" kicker="Local only" icon={<FileKey2/>} title="File Hash Generator"><p>Files are hashed locally and are not uploaded. SHA-1 and MD5 are included only for legacy comparison and should not be used as modern integrity guarantees.</p><div className="nv-form"><input className="nv-input" type="file" onChange={e=>{setFile(e.target.files?.[0]||null);setHashes(null)}}/>{file&&<span className="nv-muted">{file.name} • {(file.size/1024/1024).toFixed(2)} MB</span>}<button className="nv-button nv-button-primary" onClick={run}>Generate hashes</button></div>{hashes&&<div className="nv-result">{Object.entries(hashes).map(([k,v])=><div key={k} style={{marginBottom:12}}><strong>{k.toUpperCase()}</strong>{k!=='sha256'&&<span className="nv-status-warn"> • legacy/insecure for security decisions</span>}<p className="nv-code">{v}</p><button className="nv-button" onClick={()=>navigator.clipboard.writeText(String(v))}><Copy size={14}/>Copy</button></div>)}<p><strong>Hash matching alone does not prove a file is safe.</strong></p><a className="nv-button" href={`https://www.virustotal.com/gui/file/${hashes.sha256}`} target="_blank" rel="noreferrer">Search SHA-256 on VirusTotal <ExternalLink size={14}/></a></div>}</ToolShell>}

function DomainCheck(){const [domain,setDomain]=useState('');return <ToolShell id="domain-check" kicker="Adapter ready" icon={<Globe2/>} title="Basic Domain Safety Check"><p>Passive server-side checks can include DNS, SPF/DMARC, redirects and selected security headers. To prevent SSRF and unsafe arbitrary fetching, this feature is intentionally disabled until the protected Supabase Edge Function in this project is deployed.</p><input className="nv-input" value={domain} onChange={e=>setDomain(e.target.value)} placeholder="example.com"/><div className="nv-result"><h4 className="nv-status-warn">Advanced automatic verification coming later</h4><p>Current free static hosting cannot safely perform protected server-side domain requests. The supplied Edge Function scaffold blocks localhost, private/reserved ranges, metadata addresses, excessive redirects and large responses.</p></div></ToolShell>}

const checklistProfiles:Record<string,string[]>={
  'iPhone':['Enable a strong device passcode','Turn on Find My iPhone','Review iOS updates','Review app permissions','Enable account recovery and MFA'],
  'Android':['Use a strong screen lock','Enable Find My Device','Install Android security updates','Review app permissions','Enable account MFA'],
  'Facebook':['Use a unique password','Enable 2FA','Review active sessions','Review connected apps','Enable login alerts'],
  'Instagram':['Use a unique password','Enable 2FA','Review login activity','Verify recovery email/phone','Watch for fake support DMs'],
  'WhatsApp':['Enable two-step verification','Set a secure voicemail PIN','Review linked devices','Enable chat backup protection if available','Never share verification codes'],
  'Gmail':['Use a unique password','Enable 2-Step Verification','Review security activity','Check recovery methods','Review third-party access'],
  'Website owner':['Enable MFA on hosting/domain','Patch CMS and plugins','Use backups','Set security headers','Review admin accounts'],
  'Student':['Use a password manager','Enable MFA on email','Keep laptop/phone updated','Back up assignments','Verify scholarship/job links']
};
function Checklist(){const [profile,setProfile]=useState('Student');const [done,setDone]=useState<Record<string,boolean>>({});const items=checklistProfiles[profile];const pct=Math.round(items.filter(i=>done[i]).length/items.length*100);return <ToolShell id="security-checklists" kicker="Free • Local save" icon={<Smartphone/>} title="Security Checklist Generator"><select className="nv-input" value={profile} onChange={e=>{setProfile(e.target.value);setDone({})}}>{Object.keys(checklistProfiles).map(x=><option key={x}>{x}</option>)}</select><div className="nv-card-footer"><strong>{pct}% complete</strong><span>{items.filter(i=>done[i]).length}/{items.length}</span></div><div className="nv-progress"><span style={{width:`${pct}%`}}/></div><div className="nv-checklist" style={{marginTop:14}}>{items.map(x=><label className="nv-checkitem" key={x}><input type="checkbox" checked={!!done[x]} onChange={e=>setDone(d=>({...d,[x]:e.target.checked}))}/><span>{x}</span></label>)}</div><div className="nv-report-actions"><button className="nv-button nv-button-primary" onClick={()=>generateNexVibePdf({title:`${profile} Security Checklist`,type:'Personal Security Checklist',summary:`${pct}% of selected checklist items are complete.`,findings:items.map(i=>`${done[i]?'Completed':'Pending'}: ${i}`),actions:items.filter(i=>!done[i])})}><Download size={15}/>PDF checklist</button><button className="nv-button" onClick={()=>setDone({})}>Reset</button></div></ToolShell>}

export default function DigitalSafety(){const location=useLocation();useEffect(()=>{const id=location.pathname.split('/').pop();if(id&&id!=='digital-safety')setTimeout(()=>document.getElementById(id)?.scrollIntoView({behavior:'smooth'}),50)},[location.pathname]);return <><PageHero eyebrow="NexVibe Digital Safety Centre" title="Free-first checks with honest limitations" lead="No tool here claims that a person, password, URL, QR code, file or domain is completely safe. Sensitive checks stay local where possible."/><section className="nv-section-compact"><div className="nv-container nv-tool-layout"><PasswordChecker/><EmailSafety/><UrlChecker/><QrChecker/><FileHash/><DomainCheck/><Checklist/><ToolShell id="reports" kicker="Local PDF" icon={<ShieldCheck/>} title="NexVibe PDF Reports"><p>Generate branded reports from supported safety tools. Reports include the NexVibe logo, local report ID, findings, limitations, privacy notice, responsible-use statement and watermark.</p><div className="nv-result"><h4>No cloud save by default</h4><p>Reports are generated in your browser and are not emailed or permanently saved without explicit action.</p></div></ToolShell></div></section><section className="nv-section-compact"><div className="nv-container nv-card" style={{padding:22}}><h3>More safety intelligence</h3><p className="nv-muted">Search the official CISA Known Exploited Vulnerabilities catalog and cached NVD records from NexVibe’s CVE explorer.</p><Link className="nv-button" to="/cve">Open CVE & CISA KEV Explorer</Link></div></section></>}
