import { useMemo, useState } from 'react';
import { ExternalLink, Github, Search } from 'lucide-react';
import { PageHero, EmptyState } from '../components/Common';
import { courses, roadmaps, toolDirectory } from '../data/manual';
import { useKev, useNvd } from '../lib/live';
import { officialSources } from '../lib/config';

export function ToolsPage({osintOnly=false}:{osintOnly?:boolean}){
  const [q,setQ]=useState(''); const [cat,setCat]=useState('all'); const [pricing,setPricing]=useState('all');
  const items=useMemo(()=>toolDirectory.filter(t=>!osintOnly||/OSINT|Metadata|Threat Intelligence|Geolocation|Archives|Fact/i.test(t.category+t.description)),[osintOnly]);
  const cats=[...new Set(items.map(x=>x.category))];
  const filtered=items.filter(x=>(cat==='all'||x.category===cat)&&(pricing==='all'||x.pricing===pricing)&&(!q||`${x.name} ${x.description} ${x.category}`.toLowerCase().includes(q.toLowerCase())));
  return <><PageHero eyebrow={osintOnly?'OSINT Directory':'Cyber & Digital Tools'} title={osintOnly?'OSINT tools for responsible research':'Curated tools with official links'} lead="Every listing includes an official URL, difficulty, pricing and safety classification. NexVibe does not execute offensive actions for visitors."/>
    <section className="nv-section-compact"><div className="nv-container"><div className="nv-toolbar"><input className="nv-input" value={q} onChange={e=>setQ(e.target.value)} placeholder="Search tools…"/><select className="nv-input nv-filter-select" value={cat} onChange={e=>setCat(e.target.value)}><option value="all">All categories</option>{cats.map(c=><option key={c}>{c}</option>)}</select><select className="nv-input nv-filter-select" value={pricing} onChange={e=>setPricing(e.target.value)}><option value="all">Free / paid</option><option>Free</option><option>Freemium</option><option>Paid</option></select></div><div className="nv-grid-3">{filtered.length?filtered.map(t=><article key={t.id} className="nv-card nv-card-hover nv-directory-card"><div className="nv-meta"><span className="nv-chip">{t.category}</span><span className="nv-chip">{t.classification}</span></div><h3>{t.name}</h3><p>{t.description}</p><div className="nv-meta" style={{marginTop:12}}><span>{t.pricing}</span><span>{t.difficulty}</span><span>{t.platforms.join(', ')}</span><span>Verified {t.lastVerified}</span></div><div className="nv-card-footer"><a className="nv-button" href={t.officialUrl} target="_blank" rel="noreferrer">Official <ExternalLink size={14}/></a>{t.githubUrl&&<a className="nv-button" href={t.githubUrl} target="_blank" rel="noreferrer"><Github size={14}/>GitHub</a>}</div></article>):<EmptyState/>}</div></div></section>
  </>
}

export function CoursesPage({coupons=false}:{coupons?:boolean}){
  if(coupons) return <><PageHero eyebrow="Deals" title="Coupons & verified learning deals" lead="NexVibe does not fabricate prices or coupon codes. Manual review is required before a deal is published."/><section className="nv-section-compact"><div className="nv-container"><div className="nv-card" style={{padding:26}}><h2 style={{marginTop:0}}>No verified coupons are currently available.</h2><p className="nv-muted">This area is ready for admin-managed Udemy, Coursera, TryHackMe, Hack The Box and other verified provider deals. Expired or unverified codes should not be shown.</p></div></div></section></>;
  return <><PageHero eyebrow="Learning Deals" title="Courses from verified providers" lead="Listings point to the provider's official page. No protected-course scraping and no fake discounts."/><section className="nv-section-compact"><div className="nv-container nv-grid-3">{courses.map(c=><article key={c.id} className="nv-card nv-card-hover nv-directory-card"><span className="nv-chip">{c.pricing}</span><h3>{c.title}</h3><p>{c.provider}</p><div className="nv-meta" style={{marginTop:12}}><span>{c.level}</span><span>{c.language}</span><span>{c.duration}</span><span>{c.certificate}</span></div><div className="nv-card-footer"><span className="nv-muted">Verified {c.lastVerified}</span><a className="nv-button" href={c.officialUrl} target="_blank" rel="noreferrer">Official <ExternalLink size={14}/></a></div></article>)}</div></section></>
}

export function LearnPage({roadmapOnly=false}:{roadmapOnly?:boolean}){
  return <><PageHero eyebrow="Learning Centre" title={roadmapOnly?'Cybersecurity & digital roadmaps':'Learn with a clear path'} lead="Ordered learning paths with free-first resources, labs and responsible-use guidance."/><section className="nv-section-compact"><div className="nv-container nv-grid-2">{roadmaps.map(r=><article id={r.id} key={r.id} className="nv-card" style={{padding:22,scrollMarginTop:100}}><span className="nv-chip">Roadmap</span><h2 style={{margin:'.6rem 0'}}>{r.title}</h2><ol className="nv-muted">{r.steps.map(s=><li key={s} style={{marginBottom:6}}>{s}</li>)}</ol></article>)}</div></section></>
}

export function CvePage(){
  const {data,loading,error}=useKev(); const {data:nvd}=useNvd(); const [q,setQ]=useState('');
  const kev=(data.vulnerabilities||[]).filter(v=>!q||`${v.cveID} ${v.vendorProject} ${v.product} ${v.vulnerabilityName}`.toLowerCase().includes(q.toLowerCase())).slice(0,100);
  const nvdItems=(nvd.items||[]).filter(v=>!q||`${v.id} ${v.description}`.toLowerCase().includes(q.toLowerCase())).slice(0,40);
  return <><PageHero eyebrow="Vulnerability Intelligence" title="CVE & CISA Known Exploited Vulnerabilities" lead="Official CISA KEV data is synced into the site by GitHub Actions. NVD data is cached separately and never fabricated."/><section className="nv-section-compact"><div className="nv-container"><div className="nv-toolbar"><input className="nv-input" value={q} onChange={e=>setQ(e.target.value)} placeholder="Search CVE, vendor, product or vulnerability…"/><span className="nv-muted">KEV {data.count||kev.length}</span></div>{loading?<div className="nv-card" style={{padding:22}}>Loading cached official data…</div>:error?<div className="nv-card" style={{padding:22}}>KEV cache unavailable until the scheduled sync runs.</div>:null}<div className="nv-grid-2">{kev.length?kev.map(v=><article key={v.cveID} className="nv-card nv-list-card"><div className="nv-meta"><span className="nv-chip">Known Exploited</span><strong>{v.cveID}</strong></div><h3>{v.vulnerabilityName}</h3><p>{v.vendorProject} • {v.product}</p><p className="nv-muted">{v.shortDescription}</p><p><strong>Required action:</strong> {v.requiredAction}</p><div className="nv-meta"><span>Added {v.dateAdded}</span><span>Due {v.dueDate||'See catalog'}</span></div><div className="nv-card-footer"><a className="nv-button" href={`https://www.cisa.gov/known-exploited-vulnerabilities-catalog?search_api_fulltext=${encodeURIComponent(v.cveID)}`} target="_blank" rel="noreferrer">CISA <ExternalLink size={14}/></a></div></article>):<EmptyState title="KEV data will appear after sync" body="The GitHub Action fetches the official CISA JSON and writes public/data/kev.json."/>}</div>{nvdItems.length>0&&<><h2 className="nv-title" style={{fontSize:'2rem',marginTop:42}}>Recent NVD records</h2><div className="nv-grid-2">{nvdItems.map(v=><article key={v.id} className="nv-card nv-list-card"><div className="nv-meta"><strong>{v.id}</strong>{v.severity&&<span className="nv-chip">{v.severity}</span>}</div><p>{v.description}</p><div className="nv-card-footer"><span className="nv-muted">{v.published}</span><a className="nv-button" href={v.url} target="_blank" rel="noreferrer">NVD <ExternalLink size={14}/></a></div></article>)}</div></>}</div></section></>
}

export function GitHubPage(){
  const repos=toolDirectory.filter(t=>t.githubUrl);
  return <><PageHero eyebrow="GitHub Directory" title="Verified project repositories" lead="Only manually verified project links are shown. Live stars, forks or release counts are intentionally hidden unless verified at runtime."/><section className="nv-section-compact"><div className="nv-container nv-grid-3">{repos.map(r=><article key={r.id} className="nv-card nv-directory-card"><span className="nv-chip">{r.classification}</span><h3>{r.name}</h3><p>{r.description}</p><div className="nv-card-footer"><span className="nv-muted">Last verified {r.lastVerified}</span><a className="nv-button" href={r.githubUrl} target="_blank" rel="noreferrer"><Github size={14}/>Repository</a></div></article>)}</div></section></>
}

export function OfficialSourcesPage(){
  return <><PageHero eyebrow="Official Sources" title="Primary sources bound to NexVibe" lead="Use these authority and vendor websites to verify alerts, vulnerability details, security releases and learning information."/><section className="nv-section-compact"><div className="nv-container nv-grid-3">{officialSources.map(s=><a key={s.name} href={s.url} target="_blank" rel="noreferrer" className="nv-card nv-card-hover nv-list-card"><span className="nv-chip">Official</span><h3>{s.name}</h3><p>{s.description}</p><div className="nv-card-footer"><span className="nv-muted">Primary source</span><ExternalLink size={17}/></div></a>)}</div></section></>
}
