import { useState } from 'react';
import { ExternalLink, Facebook, Mail, MessageCircle, Music2 } from 'lucide-react';
import { PageHero } from '../components/Common';
import { siteConfig } from '../lib/config';

export function Services(){return <><PageHero eyebrow="NexVibe Services" title="Build your next digital presence" lead="Responsive websites, content systems, AI creative support, branding and cybersecurity-awareness content — without fake payment flows."/><section className="nv-section-compact"><div className="nv-container nv-grid-3">{[
['Website Development','Mobile-first websites, landing pages and GitHub Pages-ready deployments.'],['Social Media Content','Branded posts, captions, thumbnails and content systems for Facebook, TikTok and Instagram.'],['AI Image / Video Prompts','Production-ready prompts for visual and short-form video creation.'],['Digital Branding','Logo usage systems, brand visuals, social kits and consistent digital identity.'],['Cybersecurity Awareness Content','Educational posts, explainers, digital-safety guides and defensive cyber content.'],['Digital Templates & Resources','Reusable templates, checklists, guides and learning resources.']
].map(([t,d])=><article className="nv-card nv-card-hover nv-directory-card" key={t}><span className="nv-chip">Service</span><h3>{t}</h3><p>{d}</p><div className="nv-card-footer"><a className="nv-button" href={`mailto:${siteConfig.email}?subject=${encodeURIComponent(`NexVibe service enquiry: ${t}`)}`}>Request quote</a></div></article>)}</div></section></>}

export function Contact(){const [name,setName]=useState('');const [message,setMessage]=useState('');return <><PageHero eyebrow="Contact NexVibe" title="Talk to NexVibe" lead="Use the official email or social links below. The static site does not send form data to a paid email service."/><section className="nv-section-compact"><div className="nv-container nv-grid-2"><div className="nv-card" style={{padding:22}}><h2 style={{marginTop:0}}>Official contact details</h2><div className="nv-checklist"><a className="nv-checkitem" href={`mailto:${siteConfig.email}`}><Mail/><span><strong>Email</strong><br/>{siteConfig.email}</span></a><a className="nv-checkitem" href={siteConfig.facebook} target="_blank" rel="noreferrer"><Facebook/><span><strong>Facebook</strong><br/>NexVibe Facebook page</span><ExternalLink size={15}/></a><a className="nv-checkitem" href={siteConfig.tiktok} target="_blank" rel="noreferrer"><Music2/><span><strong>TikTok</strong><br/>@nexvibeofficial</span><ExternalLink size={15}/></a></div></div><form className="nv-card nv-form" style={{padding:22}} onSubmit={e=>{e.preventDefault();location.href=`mailto:${siteConfig.email}?subject=${encodeURIComponent(`NexVibe enquiry from ${name||'website visitor'}`)}&body=${encodeURIComponent(message)}`}}><div className="nv-field"><label>Name</label><input className="nv-input" value={name} onChange={e=>setName(e.target.value)} required/></div><div className="nv-field"><label>Message</label><textarea className="nv-input" value={message} onChange={e=>setMessage(e.target.value)} required/></div><button className="nv-button nv-button-primary" type="submit"><MessageCircle size={17}/>Open email app</button><small className="nv-muted">This free-first version uses your device's email app instead of a paid contact-form service.</small></form></div></section></>}

export function About(){return <><PageHero eyebrow="About" title="NexVibe Cyber & Digital Hub" lead="Learn. Investigate. Secure. Build."/><section className="nv-section-compact"><div className="nv-container nv-grid-2"><div className="nv-card" style={{padding:22}}><h2>What NexVibe is building</h2><p className="nv-muted">A mobile-first hub for cybersecurity students, ethical-hacking learners, OSINT researchers, AI and tech enthusiasts, Sri Lankan students, young professionals, creators and people who want safer digital habits.</p></div><div className="nv-card" style={{padding:22}}><h2>What makes it different</h2><p className="nv-muted">Free-first architecture, clear source links, no fabricated security results, no fake coupons, honest limitations, official-source cyber intelligence and a content-management path that can grow into Supabase.</p></div></div></section></>}

export function Community(){return <><PageHero eyebrow="Community" title="Share useful digital knowledge" lead="Community submissions are designed to remain pending until admin approval. This avoids automatic publication of unverified tools, coupons, events or resources."/><section className="nv-section-compact"><div className="nv-container nv-grid-3"><article className="nv-card nv-list-card"><span className="nv-chip">Submit</span><h3>Tools & repositories</h3><p>Suggest an official tool or GitHub repository with source URL and responsible-use confirmation.</p></article><article className="nv-card nv-list-card"><span className="nv-chip">Submit</span><h3>Courses & events</h3><p>Share a verified official provider page, course, webinar or CTF for admin review.</p></article><article className="nv-card nv-list-card"><span className="nv-chip">Follow</span><h3>NexVibe socials</h3><p>Follow the latest NexVibe posts on Facebook and TikTok.</p><div className="nv-card-footer"><a className="nv-button" href={siteConfig.facebook} target="_blank" rel="noreferrer">Facebook</a><a className="nv-button" href={siteConfig.tiktok} target="_blank" rel="noreferrer">TikTok</a></div></article></div></section></>}

export function StaticPolicy({kind}:{kind:'privacy'|'terms'|'responsible'|'affiliate'}){
  const map={privacy:{title:'Privacy Policy',body:['NexVibe minimises data collection on sensitive-tool pages. Password checks do not store raw passwords, and local reports are not uploaded by default.','Optional Supabase accounts, bookmarks and submissions are only enabled when the project owner configures the free-tier backend and its row-level security policies.']},terms:{title:'Terms of Use',body:['NexVibe content is educational and informational. Always verify security, legal, financial and technical decisions against primary sources.','Do not misuse tools or information for unauthorised access, fraud, harassment or unlawful surveillance.']},responsible:{title:'Responsible Use Policy',body:['NexVibe provides educational and defensive cybersecurity resources. Use security and OSINT tools only for lawful purposes and only on systems or data you own or are explicitly authorised to investigate.','Dual-use tools are labelled. NexVibe does not build attack execution into this website.']},affiliate:{title:'Affiliate Disclosure',body:['If NexVibe later uses affiliate links, they should be clearly identified near the relevant content.','No affiliate relationship should change editorial verification or cause fake discounts, prices or coupons to be published.']}} as const;const d=map[kind];return <><PageHero eyebrow="Policy" title={d.title}/><section className="nv-section-compact"><div className="nv-container nv-card nv-prose" style={{padding:24}}>{d.body.map(p=><p key={p}>{p}</p>)}</div></section></>}

export function Saved(){return <><PageHero eyebrow="Saved" title="Your saved NexVibe content" lead="Bookmarks use local browser storage in this static build. Supabase-backed account sync can be enabled later."/><section className="nv-section-compact"><div className="nv-container nv-card" style={{padding:26}}><p className="nv-muted">No saved items yet. The route and storage model are ready for future user-account bookmarks.</p></div></section></>}
